### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by ladykorine** [EpicUnknown/wco-dl#17]
I'm not able to get either executable to work on neither my main computer or my laptop. When attempting to download anything, I just get an error "Download for (videoname here) did not complete, please try again." Both systems are Windows 10

Looking in the error logs I get nothing that shows an error being thrown. 

Was unable to get the script to run at all on Kali. The error there is that 'requests' isn't recognized and I was unable to get that installed. 

On Ubuntu I get the following traceback:

Traceback (most recent call last):
  File "./__main__.py", line 11, in <module>
    class Main():
  File "./__main__.py", line 65, in Main
    Lifter(url=args.input[0], resolution=args.highdef, logger=logger, season=args.season,
  File "/home/brin/Downloads/wco-dl-2020-01-27/Lifter.py", line 43, in __init__
    self.download_show(url, season, ep_range, exclude, output)
  File "/home/brin/Downloads/wco-dl-2020-01-27/Lifter.py", line 147, in download_show
    download_url = self.find_download_link(item)
  File "/home/brin/Downloads/wco-dl-2020-01-27/Lifter.py", line 85, in find_download_link
    ending_number = int(re.search(' - ([0-9]+)', script_url).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

I followed the directions to the letter multiple times and I can't get this to work. I'm at a lost for what I'm doing wrong.

**Comment by EpicUnknown** [comment]
Please try the new release as I just updated the file with patches that should have fixed this.

If it still does not fix it please let me know!
