### ISSUE TITLE
download for x did not complete, please try again

### ISSUE THREAD

**Issue by barkermn01** [EpicUnknown/wco-dl#19]
Firstly thanks for this awesome tool. secondly, I was testing how it works with a specific page for anime that came to my mind Sword Art Online. 

For some reason with the first season it error with 

```
python .\src\__main__.py -i https://www.wcostream.com/anime/sword-art-online
Settings Loaded.
Downloading show
[wco-dl] - Downloading Sword-Art-Online-Extra-Edition-English-Dubbed-2-S01E00-
0it [00:00, ?it/s]
[wco-dl] - Download for Sword-Art-Online-Extra-Edition-English-Dubbed-2-S01E00- did not complete, please try again.

[wco-dl] - Downloading Sword Art Online-S01E25-English Dubbed 2
[wco-dl] - Download for Sword Art Online-S01E25-English Dubbed 2 did not complete, please try again.
```

I spent ages going through the code could not work out why it was failing, then went to issues and could see people were trying other stuff so I tried SAO 2 and it worked perfectly, so not sure why it's failing on a specific page after much testing it's the only one I can find that has that problem.

**Comment by EpicUnknown** [comment]
I've noticed to have that problem as well with some other Anime's and Cartoon's. I'm not sure if the traffic is being stopped or if the website realizes that it's a Scrapper bot and kills the connection.

I have been fighting with this since I've made this little script haha. My other script (MyAnimeDownloader) has the same problem.

**Comment by MrCtje** [comment]
https://github.com/EpicUnknown/wco-dl/blob/8f90d0d558e80f74dbea8feb2c3e68db6718cf56/Lifter.py#L242

I've encountered the same issue, I don't know what the real issue is but the backup url works for me.

**Comment by barkermn01** [comment]
I'm not sure i used an online downloader and found that the backup URL was working but the primary was not, perhaps instead of just erroring and stopping on the failure to download it fails then tries the backup URL to see if that works?

Just a possible fix

**Comment by EpicUnknown** [comment]
Sounds good. I'll make it try the backup URL when I get home tonight and hopefully push out a fix.

Thank you for using it and providing feedback! It's greatly appreciated!

**Comment by EpicUnknown** [comment]
This issue is finally resolved and I uploaded a new EXE with the working version.
