### ISSUE TITLE
Directory not Found

### ISSUE THREAD

**Issue by leptoid** [EpicUnknown/wco-dl#7]
When choosing a directory to save to, script fails if directory does not already exist.  Script should:
 check for path
        if not exist, create it
        elseif exist, use it

Could default to .\output\show name  if no input given

**Comment by leptoid** [comment]
#Feature

**Comment by EpicUnknown** [comment]
@leptoid

The script **SHOULD** default to `./Output/ShowName`

Does it not?

**Comment by leptoid** [comment]
My mistake.  Maybe I was doing it wrong.  No output directory will create a path.  Manual path that does not exist will error, not test/create path.

**Comment by EpicUnknown** [comment]
Gotcha, I will add that tonight to a small hotfix. I'll ensure it displays that you put a non-existent path in and make it default to "Output". Eventually, one day I'll make a `settings.json` so you can make it forcefully make the Output you designated exist, if wanted.

**Comment by leptoid** [comment]
I think that would be a good way to approach it.
